services:
  m3u8-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/zaocorelabs/m3u8-proxy
    container_name: m3u8-proxy
    ports:
      - "9005:8080"
    environment:
      - HOST="localhost"
      - PORT="8080"
      - PUBLIC_URL="https://proxy.1ani.me"
    restart: unless-stopped